version: "3.3"

networks:
  swarm_net:
    external: true

services:
  runs_adapter:
    image: $REGISTRY/runs_adapter  
    networks:
      - swarm_net
    ports:
      - 8090:8090
    deploy:
        replicas: 1
        resources:
          limits:
            cpus: "0.1"
            memory: '50M'
        placement: 
            constraints: [node.role != manager]
    labels:
      org.label-schema.group: "nt_service"

  